## Stage 1: Dependencies
FROM node:20-bookworm-slim AS deps
RUN apt-get update && apt-get install -y libc6 python3 make g++ && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
# Install pnpm and configure it for the target platform
RUN npm install -g pnpm && \
    pnpm config set supportedArchitectures.os linux && \
    pnpm config set supportedArchitectures.cpu x64 && \
    pnpm install --no-frozen-lockfile

## Stage 2: Builder
FROM node:20-bookworm-slim AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# We disable telemetry to improve build speed
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm install -g pnpm && pnpm run build

## Stage 3: Runner
FROM node:20-bookworm-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy the standalone output folder generated by Next.js
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
ENV PORT=3000

# Start the server
CMD ["node", "server.js"]
